[package]
name = "jotunheim"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
prometheus = "*"
async-std = { version = "*", features = ["attributes", "unstable", "tokio1"] }
anyhow = "*"
xactor = "*"
async-trait = "*"
tide = "*"
log = "*"
bme680 = { version = "*", optional = true }
embedded-hal = { version = "*", optional = true }
linux-embedded-hal = { version = "*", optional = true }
i2cdev = { version = "*", optional = true }
futures-util = "*"
uuid = { version = "0.8", features = ["serde", "v4"] }
clap = "*"
envconfig = "0.10"
env_logger = "*"
env = "*"
rust_gpiozero = { git = "https://github.com/rahul-thakoor/rust_gpiozero.git", version = "*", optional = true }
reqwest = { version = "0.11", features = ["rustls-tls"] }
dyn-fmt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[features]
default = ["sensor-bme680", "switch-gpio", "sensor-external"]
sensor-bme680 = ["bme680", "embedded-hal", "linux-embedded-hal"]
switch-gpio = ["rust_gpiozero"]
sensor-external = []
